name: Build & run AOC

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DAYS_COMPLETED: 2

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run
      run: |
        DAY=1
        while [ $DAY -le $DAYS_COMPLETED ]; do
          PROJECT=day$(printf %02d $DAY)
          cargo run -p $PROJECT -- $PROJECT/input.txt
          DAY=$(( DAY + 1 ))
        done
